name: Continuous integration
on:
  pull_request:
  push:
    branches-ignore:
      - master
jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install
      - name: Test code style
        run: vendor/bin/ecs
      - name: Static analysis (phpstan)
        run: vendor/bin/phpstan
      - name: Static analysis (psalm)
        run: vendor/bin/psalm
      - name: Tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
  commitlint:
    name: commit-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ../../commitlint.config.js
