permissions:
  contents: read

name: Release
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install
      - name: Test code style
        run: vendor/bin/ecs
      - name: Static analysis (phpstan)
        run: vendor/bin/phpstan
      - name: Static analysis (psalm)
        run: vendor/bin/psalm
      - name: Tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
  release:
    name: Automated release
    permissions:
      contents: write # Required by semantic-release to publish GitHub releases.
    needs: [ code_checks ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '21'
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p "@semantic-release/github"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
