name: Release
on:
  push:
    branches:
      - master
jobs:
  code_checks:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install
      - name: Test code style
        run: vendor/bin/ecs
      - name: Static analysis (phpstan)
        run: vendor/bin/phpstan
      - name: Static analysis (psalm)
        run: vendor/bin/psalm
      - name: Tests
        run: vendor/bin/phpunit --coverage-clover coverage.xml
  release:
    name: Automated release
    needs: [ code_checks ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: >
          npx
          -p "@semantic-release/commit-analyzer"
          -p "@semantic-release/release-notes-generator"
          -p "@semantic-release/github"
          -p conventional-changelog-conventionalcommits
          -p semantic-release
          -- semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
